
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class companydetails extends javax.swing.JFrame {

    /**
     * Creates new form companydetails
     */
    public companydetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        companyname = new javax.swing.JTextField();
        cmmlevel = new javax.swing.JTextField();
        recruit_no = new javax.swing.JTextField();
        annualpackage = new javax.swing.JTextField();
        phn_no = new javax.swing.JTextField();
        percentage10 = new javax.swing.JTextField();
        percentage12 = new javax.swing.JTextField();
        btechpercentage = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        names1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Company Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(34, 160, 189, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CMM Level");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(34, 211, 128, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No.of.Recruitments");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(34, 268, 234, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Annual Package");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(34, 318, 189, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(34, 376, 182, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Percentage in 10th");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(23, 426, 226, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Percentage in 12th");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(23, 481, 226, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Percentage in B.Tech");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(23, 532, 252, 29);
        jPanel1.add(companyname);
        companyname.setBounds(542, 156, 254, 33);
        jPanel1.add(cmmlevel);
        cmmlevel.setBounds(542, 207, 254, 33);
        jPanel1.add(recruit_no);
        recruit_no.setBounds(542, 263, 254, 34);
        jPanel1.add(annualpackage);
        annualpackage.setBounds(542, 315, 254, 32);
        jPanel1.add(phn_no);
        phn_no.setBounds(542, 373, 254, 32);
        jPanel1.add(percentage10);
        percentage10.setBounds(542, 423, 254, 32);
        jPanel1.add(percentage12);
        percentage12.setBounds(542, 479, 254, 31);
        jPanel1.add(btechpercentage);
        btechpercentage.setBounds(542, 528, 254, 33);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 590, 110, 40);

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(550, 590, 110, 40);

        names1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        names1.setForeground(new java.awt.Color(51, 255, 204));
        jPanel1.add(names1);
        names1.setBounds(990, 632, 0, 0);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Online Placement");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(330, 40, 318, 44);

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(700, 590, 110, 40);

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(770, 30, 71, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo-1486406146926-c627a92ad1ab.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 940, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/placement_system","root","");
            String sql = "INSERT INTO company_details (companyname, cmmlevel, recruit_no, annualpackage, phn_no, percentage10, percentage12,btechpercentage)"+"VALUES(?,?,?,?,?,?,?,?)";
           
            PreparedStatement pst =  con.prepareStatement(sql);
            pst.setString(1, companyname.getText());
            pst.setString(2, cmmlevel.getText());
            pst.setString(3, recruit_no.getText());
            pst.setString(4, annualpackage.getText());
            pst.setString(5, phn_no.getText());
            pst.setString(6, percentage10.getText());
            pst.setString(7, percentage12.getText());
            pst.setString(8, btechpercentage.getText());
            
            
            
            
            
            pst.execute();
            
           
            JOptionPane.showMessageDialog(null,"Added Successfully");
            companysummary pot = new companysummary();
            pot.setVisible(true);
            setVisible(false);
            
            con.close();
            
        }
        catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try{
                String value1 = companyname.getText();
                String value2 = cmmlevel.getText();
                String value3 = recruit_no.getText();
                String value4 = annualpackage.getText();
                String value5 = phn_no.getText();
                String value6 = percentage10.getText();
                String value7 = percentage12.getText();
                String value8 = btechpercentage.getText();
                
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/placement_system", "root", "");
                String sql = "UPDATE company_details SET cmmlevel='"+value2+"', recruit_no='"+value3+"', annualpackage='"+value4+"', phn_no='"+value5+"', percentage10='"+value6+"', percentage12='"+value7+"', btechpercentage='"+value8+"' WHERE companyname='"+value1+"' ";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Updated");
                
                con.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String x = companyname.getText();
        companysummary pot = new companysummary();
        pot.Name.setText(x);
        pot.displayname.setText(x);
        pot.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        companylogin pot = new companylogin();
        pot.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(companydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(companydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(companydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(companydetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new companydetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annualpackage;
    private javax.swing.JTextField btechpercentage;
    private javax.swing.JTextField cmmlevel;
    public static javax.swing.JTextField companyname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel names1;
    private javax.swing.JTextField percentage10;
    private javax.swing.JTextField percentage12;
    private javax.swing.JTextField phn_no;
    private javax.swing.JTextField recruit_no;
    // End of variables declaration//GEN-END:variables
}
