
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class studentselection extends javax.swing.JFrame {

    /**
     * Creates new form studentselection
     */
    public studentselection() {
        initComponents();
        show_user();
    }
    
    public ArrayList<User> userList(){
         ArrayList<User> usersList = new ArrayList<>();
          try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/placement_system","root","");
            String query1 = "SELECT * FROM  company_details";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            User user;
            while(rs.next()){
                user = new User(rs.getInt("sno"),rs.getString("companyname"),rs.getInt("cmmlevel"),rs.getInt("recruit_no"),rs.getInt("annualpackage"),rs.getInt("phn_no"),rs.getInt("percentage10"),rs.getInt("percentage12"),rs.getInt("btechpercentage"));
                usersList.add(user);
            }
        }
           catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
          return usersList;
    }
    
    public void show_user(){
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)jTable1_Display_User.getModel();
        Object[] row = new Object[9];
        for(int i=0;i<list.size();i++){
            row[0] = list.get(i).getsno();
            row[1] = list.get(i).getcompanyname();
            row[2] = list.get(i).getcmmlevel();
            row[3] = list.get(i).getrecruit_no();
            row[4] = list.get(i).getannualpackage();
            row[5] = list.get(i).getphn_no();
            row[6] = list.get(i).getpercentage10();
            row[7] = list.get(i).getpercentage12();
            row[8] = list.get(i).getbtechpercentage();
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        companyname = new javax.swing.JTextField();
        cmmlevel = new javax.swing.JTextField();
        recruit_no = new javax.swing.JTextField();
        annualpackage = new javax.swing.JTextField();
        phn_no = new javax.swing.JTextField();
        percentage10 = new javax.swing.JTextField();
        percentage12 = new javax.swing.JTextField();
        btechpercentage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_Display_User = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        names1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cgpa = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Company Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(31, 130, 189, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("CMM Level");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(31, 194, 128, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("No.of.Recruitments");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(31, 252, 234, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Annual Packages");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(31, 306, 234, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Mobile Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(31, 360, 182, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Percentage in 10");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(31, 415, 201, 29);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Percentage in 12");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(31, 470, 201, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("btechPercentage ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(31, 525, 209, 29);

        companyname.setEditable(false);
        jPanel1.add(companyname);
        companyname.setBounds(354, 130, 189, 33);

        cmmlevel.setEditable(false);
        jPanel1.add(cmmlevel);
        cmmlevel.setBounds(354, 190, 189, 33);

        recruit_no.setEditable(false);
        jPanel1.add(recruit_no);
        recruit_no.setBounds(354, 248, 189, 33);

        annualpackage.setEditable(false);
        annualpackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annualpackageActionPerformed(evt);
            }
        });
        jPanel1.add(annualpackage);
        annualpackage.setBounds(354, 310, 189, 32);

        phn_no.setEditable(false);
        jPanel1.add(phn_no);
        phn_no.setBounds(354, 364, 189, 33);

        percentage10.setEditable(false);
        jPanel1.add(percentage10);
        percentage10.setBounds(354, 419, 189, 33);

        percentage12.setEditable(false);
        jPanel1.add(percentage12);
        percentage12.setBounds(354, 474, 189, 33);

        btechpercentage.setEditable(false);
        jPanel1.add(btechpercentage);
        btechpercentage.setBounds(354, 529, 189, 32);

        jTable1_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sno", "companyname", "cmmlevel", "recruit_no", "annualpackage", "phn_nol", "percentage10", "percentage12", "btechpercentagel"
            }
        ));
        jTable1_Display_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_Display_UserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_Display_User);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(560, 130, 452, 402);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 580, 130, 36);

        names1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        names1.setForeground(new java.awt.Color(0, 255, 204));
        jPanel1.add(names1);
        names1.setBounds(935, 623, 43, 0);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Online Placement");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 30, 388, 44);

        cgpa.setText("jLabel11");
        jPanel1.add(cgpa);
        cgpa.setBounds(1020, 410, 40, 14);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(890, 20, 71, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1050, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1_Display_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_Display_UserMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel)jTable1_Display_User.getModel();
        int selectedIndex = jTable1_Display_User.getSelectedRow();
        
        companyname.setText(model.getValueAt(selectedIndex, 1).toString());
        cmmlevel.setText(model.getValueAt(selectedIndex, 2).toString());
        recruit_no.setText(model.getValueAt(selectedIndex, 3).toString());
        annualpackage.setText(model.getValueAt(selectedIndex, 4).toString());
        phn_no.setText(model.getValueAt(selectedIndex, 5).toString());
        percentage10.setText(model.getValueAt(selectedIndex, 6).toString());
        percentage12.setText(model.getValueAt(selectedIndex, 7).toString());
        btechpercentage.setText(model.getValueAt(selectedIndex, 8).toString());
        
    }//GEN-LAST:event_jTable1_Display_UserMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                
                 String x = names1.getText();
                 String y = companyname.getText();
                 String z = btechpercentage.getText();
                String a = cgpa.getText();
                 company pot = new company();
                 pot.names3.setText(x);
                 pot.company.setText(y);
                 pot.btechpercentage.setText(z);
                 pot.scgpa.setText(a);
                 pot.setVisible(true);
                 setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void annualpackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annualpackageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annualpackageActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        login pot = new login();
        pot.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentselection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentselection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annualpackage;
    private javax.swing.JTextField btechpercentage;
    public static javax.swing.JLabel cgpa;
    private javax.swing.JTextField cmmlevel;
    private javax.swing.JTextField companyname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_Display_User;
    public static javax.swing.JLabel names1;
    private javax.swing.JTextField percentage10;
    private javax.swing.JTextField percentage12;
    private javax.swing.JTextField phn_no;
    private javax.swing.JTextField recruit_no;
    // End of variables declaration//GEN-END:variables
}
