
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class studentdeatils extends javax.swing.JFrame {

    /**
     * Creates new form studentdeatils
     */
    public studentdeatils() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phn_no = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        sem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        arrears = new javax.swing.JTextField();
        standingarrears = new javax.swing.JTextField();
        cgpa = new javax.swing.JTextField();
        percentage12 = new javax.swing.JTextField();
        percentage10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        names = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(71, 128, 152, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(71, 188, 66, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(71, 253, 182, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("year");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(71, 399, 52, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(71, 327, 170, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sem");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(71, 467, 52, 29);
        jPanel1.add(name);
        name.setBounds(330, 130, 188, 33);
        jPanel1.add(email);
        email.setBounds(328, 192, 188, 33);
        jPanel1.add(phn_no);
        phn_no.setBounds(328, 257, 188, 33);
        jPanel1.add(department);
        department.setBounds(328, 323, 188, 33);
        jPanel1.add(year);
        year.setBounds(328, 395, 188, 33);
        jPanel1.add(sem);
        sem.setBounds(328, 463, 188, 33);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("History Of Arrears");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(590, 130, 213, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Standing Arrears");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(593, 188, 199, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("B.Tech Percentage");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(593, 253, 230, 29);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Percentage in 12th");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(593, 319, 226, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Percentage in 10th");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(590, 390, 226, 29);
        jPanel1.add(arrears);
        arrears.setBounds(850, 130, 203, 33);
        jPanel1.add(standingarrears);
        standingarrears.setBounds(849, 192, 203, 33);
        jPanel1.add(cgpa);
        cgpa.setBounds(849, 257, 203, 33);
        jPanel1.add(percentage12);
        percentage12.setBounds(849, 323, 203, 33);
        jPanel1.add(percentage10);
        percentage10.setBounds(850, 390, 203, 33);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(670, 480, 130, 40);

        names.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        names.setForeground(new java.awt.Color(0, 255, 204));
        jPanel1.add(names);
        names.setBounds(908, 510, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Online Placement");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(320, 40, 410, 30);

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(960, 40, 71, 23);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/work-wallpaper-hd-For-Laptop-Wallpaper.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1100, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/placement_system","root","");
            String sql = "INSERT INTO student_details (username,email,phn_no,department,year,sem,arrears,standingarrears,percentage,percentage12,percentage10)"+"VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            
            PreparedStatement pst =  con.prepareStatement(sql);
            pst.setString(1, name.getText());
            pst.setString(2, email.getText());
            pst.setString(3, phn_no.getText());
            pst.setString(4, department.getText());
            pst.setString(5, year.getText());
            pst.setString(6, sem.getText());
            pst.setString(7, arrears.getText());
            pst.setString(8, standingarrears.getText());
            pst.setString(9, cgpa.getText());
            pst.setString(10, percentage12.getText());
            pst.setString(11, percentage10.getText());
            


            
            
            pst.execute();
           
            
            
            
           
            JOptionPane.showMessageDialog(null,"Details added successfully");
            String x = names.getText();
            String y = cgpa.getText();
            studentselection pot = new studentselection();
            pot.names1.setText(x);
            pot.cgpa.setText(y);
            pot.setVisible(true);
            setVisible(false);
            
            con.close();
            
        }
        catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
        }
       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        login pot = new login();
        pot.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentdeatils.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentdeatils.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentdeatils.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentdeatils.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentdeatils().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrears;
    private javax.swing.JTextField cgpa;
    private javax.swing.JTextField department;
    public static javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField name;
    public static javax.swing.JLabel names;
    private javax.swing.JTextField percentage10;
    private javax.swing.JTextField percentage12;
    public static javax.swing.JTextField phn_no;
    private javax.swing.JTextField sem;
    private javax.swing.JTextField standingarrears;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
