
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class studentcompany extends javax.swing.JFrame {
    
    pbThread t1;

    /**
     * Creates new form studentcompany
     */
    public studentcompany() {
        initComponents();
        
        t1 = new pbThread(bar);
        t1.start();
    }
    
    class pbThread extends Thread
    {
    JProgressBar pbar;
    
    pbThread(JProgressBar pbar)
    {
        pbar = bar;         
    }
    
    public void run()
    {
       int min = 0;
       int max = 50;
       
       bar.setMaximum(min);
       bar.setMaximum(max);
       bar.setValue(0);
       
       for(int i=min;i<max;i++)
       {
          bar.setValue(i);
          
           try {
               sleep(500);
               
           } catch (InterruptedException ex) {
               Logger.getLogger(studentcompany.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       
       
               
    
    }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        progress = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        email = new javax.swing.JLabel();
        phn_no = new javax.swing.JLabel();
        Names = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);
        jPanel1.add(bar);
        bar.setBounds(120, 120, 370, 33);

        progress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        progress.setForeground(new java.awt.Color(255, 255, 255));
        progress.setText("Please Wait");
        progress.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(progress);
        progress.setBounds(250, 50, 140, 29);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 200, 107, 31);

        email.setText("jLabel3");
        jPanel1.add(email);
        email.setBounds(530, 220, 34, 14);

        phn_no.setText("jLabel4");
        jPanel1.add(phn_no);
        phn_no.setBounds(530, 180, 34, 14);
        jPanel1.add(Names);
        Names.setBounds(544, 174, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/llo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 290);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 290);

        setSize(new java.awt.Dimension(642, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String x = Names.getText();
        String y = email.getName();
        String z = phn_no.getName();
        studentdeatils pot = new studentdeatils();
        pot.names.setText(x);
        pot.name.setText(x);
        pot.email.setText(y);
        pot.phn_no.setText(z);
        pot.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentcompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentcompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentcompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentcompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Names;
    private javax.swing.JProgressBar bar;
    public static javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel phn_no;
    private javax.swing.JLabel progress;
    // End of variables declaration//GEN-END:variables
}
